name: Build CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout roothide/theos
        uses: actions/checkout@main
        with:
          repository: roothide/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: roothide/theos
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Build Package
        run: |
          brew install make xz ldid
          export THEOS=theos
          chmod +x layout/DEBIAN/*
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          archive: false
          path: packages/*.deb
